### ISSUE TITLE
Transpor pipeline de deploy do gitlab para o travis

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#261]
A fim de manter o pipeline funcionando corretamente, o deploy deve seguir a integração contínua. Por isso e pelo motivo do gitlab não dar suporte ao docker-compose nos runners compartilhados, deve-se transpor os stages de deploy para o travisci

**Tarefas**
- [x] Elaborar pipeline em stages no travis;
- [x] Preparar variáveis de configuração no travis;
- [x] Publicação de imagens no docker hub;
- [x] Deploy de homologação no heroku;
- [x] Deploy de produção no kubernetes;

**Comment by lucasca73** [comment]
Travis se portou de forma muito instável decorrente a transposição.

Dificuldades:
 - Builds condicionais não estavam se portando de acordo com o esperado.
     - condições realizadas de acordo com o demonstrado na documentação, não estavam restringindo as builds
     - alternativas foram realizadas mas nenhum sucesso.
 - Não tem como verificar a syntax do yml aceita pelo travis
    - serviço online de lint do travis esta sem fora do ar
    - lint de yml reporta como tudo ok [yaml lint](http://www.yamllint.com/) mas o travis se nega
    - serviço local de lint do travis não funciona
 - Algumas builds simplesmente não aconteciam


Build simplemente não acontece
![image](https://user-images.githubusercontent.com/4529055/48980346-d4cd4c00-f0ae-11e8-8b28-4bf7c2c78cce.png)

Serviço fora do ar
![image](https://user-images.githubusercontent.com/4529055/48980574-17445800-f0b2-11e8-8050-9fe5574ea671.png)

Lint local com [lint oficial](https://github.com/travis-ci/travis.rb#lint)
```sh
root@29d50b7411c0:/code/api-gateway# travis lint
server error (500: "Sorry, we experienced an error.\n\nrequest_id:a435b151-a44a-4650-bb94-283960936642\n")
```

Lint local com npm [travis-lint](https://www.npmjs.com/package/travis-lint)
```sh
/code/api-gateway # travis-lint .travis.yml 
/usr/local/lib/node_modules/travis-lint/cli.js:30
    if (res.length) {
            ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/travis-lint/cli.js:30:13
    at /usr/local/lib/node_modules/travis-lint/lib/travis-lint.js:18:27
    at /usr/local/lib/node_modules/travis-lint/node_modules/travis-ci/lib/travis-ci.js:51:21
    at Request._callback (/usr/local/lib/node_modules/travis-lint/node_modules/travis-ci/lib/travis-http.js:46:13)
    at Request.self.callback (/usr/local/lib/node_modules/travis-lint/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/travis-lint/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/travis-lint/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
```
